apiVersion: v1
kind: Service
metadata:
  name: app-tomcat-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: app-tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tomcat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-tomcat
  template:
    metadata:
      labels:
        app: app-tomcat
    spec:
      containers:
      - name: tomcat
        image: 8639628479/tomcatdocker:tomcatdevops
        ports:
        - containerPort: 8080
